### ISSUE TITLE
make (e=2): The system cannot find the file specified. "tmt.dll"

### ISSUE THREAD

**Issue by mendsec** [ColonelPhantom/lite-xl-tmt#6]
The commands "make" or "make mingw", generate the same error. The system cannot find the file specified. 

![image](https://user-images.githubusercontent.com/12684528/210140853-f01ce4fa-9533-41aa-9ac4-ea9316061c1d.png)

![image](https://user-images.githubusercontent.com/12684528/210140868-42d8bcae-820f-4f27-8976-3f23894f3d8a.png)

**Comment by ColonelPhantom** [comment]
It seems to try and use `cc` as C compiler, I think you need to fix that to what your actual compiler command is (maybe something like `gcc` or something mingw-related). I think you can do that by adding `CC=gcc` at the top of the Makefile, or setting the `CC` environment variable to `gcc`.

Also please be aware that the current version is kind of broken as far as I'm aware, I'm trying to fix it to use the Lite XL plugin API but there's some limitations in the current version. I hope I'll manage to get it working properly as soon as Lite XL 2.1.1 releases. It should also work on Lite XL built from the current master branch, but not sure; haven't looked at this plugin in a while. Otherwise you could try https://github.com/ColonelPhantom/lite-xl-tmt/commit/3b0f00e69ce46ca83e838c66fcdd79995a62abc8 but it also depends on Lite being built against the same Lua as TMT.

If you have Lite XL master and this plugin's current commit and it doesn't work, please let me know!

(I also did not write the Windows-related stuff of this plugin as I'm a Linux user, so if it's platform related I'm not sure how much I can help :/)

**Comment by ColonelPhantom** [comment]
Hi @fabiomen10 I just set up some CI for this plugin and now have a somewhat end-user friendly release over at https://github.com/ColonelPhantom/lite-xl-tmt/releases/latest

To install it you just download the zip/tar for your platform, and drop the `tmt` folder inside into your plugins folder.

I assume this will fix your issue, but please let me know if it works for you!
